#!/usr/bin/env bash

file=$(fd --type f --hidden --follow --exclude .git --exclude Library --exclude .Trash --exclude node_modules --exclude .DS_Store | fzf --preview "bat --style=numbers --color=always --line-range :500 {}")

if [ -n "$file" ]; then
  nvim "$file"
fi
